test/fixtures/let-binding.res 4:18 -> Did you forget a `=` here?
test/fixtures/let-binding.res 10:12 -> Did you forget a `=` here?
test/fixtures/let-binding.res 16:19 -> Did you forget a `=` here?
test/fixtures/let-binding.res 20:39 -> This let-binding misses an expression
test/fixtures/let-binding.res 22:10 -> This let-binding misses an expression
test/fixtures/let-binding.res 25:11 -> Did you forget a `=` here?
test/fixtures/let-binding.res 28:6 -> Did you forget a `=` here?
test/fixtures/let-binding.res 31:13 -> Did you forget a `=` here?
